### ISSUE TITLE
Operations on chunks (add, copy, paste, delete) no longer present in v0.7 & have some problems in 2020.06.15 versions

### ISSUE THREAD

**Issue by duffremle** [WolvenKit/Wolven-kit#240]
**Describe the bug**
v0.7 has no operations on chunks such as 'add chunk', 'copy chunk', 'paste chunk', or 'delete chunk' that are in the 2018.08.21 version. At least not that I can find. I've included some screenshots of how it was in the 2018 & the 2020.06.15 versions & how it is now in v0.7 The screenshots include a simple example of how I use this functionality. The release version of 2020.06.15 still shows this functionality & will allow me to copy a chunk but when i try to paste the chunk an exception is thrown. There's also a screenshot of this. The 2020.06.15 version allows adding a chunk then adding properties to it but building every added chunk like this (even if the properties are individually copy/pasted) is very slow & tedious compared to copying & pasting an entire chunk.   

**To Reproduce**
Shown in the screenshots

**Expected behavior**
I'd like to see these chunk operations put back in if they've been taken out or if they're still in there somewhere some documentation on how to access them. And would like to be able to copy & paste a chunk then edit it since it is much faster as a user than having to add & then build multiple chunks whose properties are mostly the same.  

**Screenshots**
I've added screenshots, they each have a bit of text description on them.
![1 2018 08 21 version allows copying an existing chunk as 1st step in adding new chunk](https://user-images.githubusercontent.com/71484892/93694021-a236e380-facc-11ea-96a0-1670b6d1cbb2.jpg)
![2 2018 08 21 version allows copied chunk to be pasted](https://user-images.githubusercontent.com/71484892/93694024-a5ca6a80-facc-11ea-8426-7da51cf583cf.jpg)
![3 2018 08 21 version copied chunk has been pasted can now edit it so its a new chunk](https://user-images.githubusercontent.com/71484892/93694027-a95df180-facc-11ea-9505-52efd790a64b.jpg)
![4 2018 08 21 version pasted chunk has been edited and now adds another armor stand](https://user-images.githubusercontent.com/71484892/93694028-ac58e200-facc-11ea-8693-8591480344b6.jpg)
![5 2020 06 15 version allows chunk copying](https://user-images.githubusercontent.com/71484892/93694030-b11d9600-facc-11ea-9e01-8e3934d96307.jpg)
![6 2020 06 15 version attempting to paste the copied chunk into the chunk list](https://user-images.githubusercontent.com/71484892/93694032-b975d100-facc-11ea-8885-c41175ac0b62.jpg)
![7 2020 06 15 throws error on pasting chunk](https://user-images.githubusercontent.com/71484892/93694041-c8f51a00-facc-11ea-9fa7-2aa30db02c28.jpg)
![8 2020 09 18 nighly version only limited functionality on the chunk list](https://user-images.githubusercontent.com/71484892/93694043-cd213780-facc-11ea-87c0-7d72f97a6887.jpg)

[Edit] As of the 9/22 nightly copy/pasta of an existing object (chunk) to make a new object (chunk) adds a new chunk to the file easily & quickly like it did in older versions, But unfortunately a new object (in this case a trophy slot) isnt added in-game. I've added the screenshots below to illustrate the steps I followed to add the new chunk & copy/pasta an existing chunk's properties into it. The file in these screenshots should be entities.w2l not entities.original.w2l but I didnt want to retake them. If i use v0.3.1 from 8/21/2018 to copy/paste an existing trophy slot chunk then edit to make it distinct, it's added in-game. So I either need to change more property values with v0.7 or something else is going on. Anyway I'm not ready to close this yet. 
![01 add new chunk via CLayer0 properties](https://user-images.githubusercontent.com/71484892/94012664-b732a180-fd6e-11ea-9bec-fe494e5b5178.jpg)
![02 new chunk same type as existing chunks](https://user-images.githubusercontent.com/71484892/94012679-bc8fec00-fd6e-11ea-92f9-da3375a5ce02.jpg)
![03 copy one of the existing chunks](https://user-images.githubusercontent.com/71484892/94012693-bf8adc80-fd6e-11ea-8f31-d4c5c31948bd.jpg)
![04 paste existing chunk into new chunk](https://user-images.githubusercontent.com/71484892/94012700-c285cd00-fd6e-11ea-93b4-457c7060b3b3.jpg)
![05 comparing the guid idTag tags transform properties shows chunk4 is a copy of chunk3](https://user-images.githubusercontent.com/71484892/94012708-c4e82700-fd6e-11ea-9c2e-b99cd3d934af.jpg)
![14 v2020 09 22 fixed changed the guid idTag tags transform properties but chunk4 not added in-game](https://user-images.githubusercontent.com/71484892/94090422-2e058400-fddb-11ea-9fa2-dd07a32592cf.jpg)
![15 v2018 98 21 fourth trophy slot added in-game when this version used to add it](https://user-images.githubusercontent.com/71484892/94091572-34492f80-fdde-11ea-9d00-2077ae794d2c.jpg)
![16 v2020 09 22 fourth trophy slot not added in-game when this version used to add it](https://user-images.githubusercontent.com/71484892/94091578-37dcb680-fdde-11ea-945d-2f09172da848.jpg)

**Desktop (please complete the following information):**
 - OS: win 7
 - Browser firefox
 - Version v80

**Additional context**
I'm hoping this is a bug because chunk operations seem to be a pretty fundamental part of editing many cr2w files. The copy & paste of an entire chunk makes the process of adding a chunk that is similar to existing chunks much faster & convenient than building each added chunk by copy/pasta of individual properties. I've added a bunch of sword stands to a entity.w2l file, this wouldnt have happened if i couldnt add chunks or had to build each added chunk from scratch.

**Comment by rfuzzo** [comment]
Hello! Thanks for the report!
Copying and Pasting chunks are soon going to be back (maybe today)

Major caveats: First, you will only be able to paste chunks of the same type into one another: so, you can copy a CMeshComponent and only paste it into another CMeshComponent. I think this is self explanatory.

Second, all chunk adding and deleting is as of 0.7 done *inside the properties of the parent chunk*. That means if you want to delete a CMeshComponent chunk, you will need to go to the parent chunk (e.g. CNewNPC, find the components array and delete the list entry there). Same goes for adding new chunks: go to the parent and edit the properties there.

We’re going to communicate all this upon release, and some things are still in the works, but that’s it.

**Comment by Maxzor** [comment]
You could also take time to [read the issue just preceding this one](#239 ), which states the current reworks point on cr2w editing.

**Comment by sodanakin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github](https://trello.com/c/V52duEWM/16-github)
